/*
 * heap_driver.c
 *
 * Simple fixed-block heap allocator using direct SRAM addressing.
 *
 * Heap region:
 *   START: 0x20001000
 *   SIZE:  4096 bytes
 *   BLOCK_SIZE: 16 bytes
 *   BLOCK_COUNT: 4096 / 16 = 256
 *
 * block_map semantics:
 *   0 = free
 *   2 = allocation head (first block of an allocation)
 *   1 = continuation block (subsequent blocks of same allocation)
 *
 * Allocation marks first block as 2 and following blocks as 1.
 * Freeing expects a pointer to the start of an allocation (block-aligned).
 * On free, the driver clears the head (2) and then clears following 1 blocks
 * until it reaches a 0 or the end of the block map.
 *
 * Notes:
 * - This implementation uses an extern UART handle named huart1 for tracing.
 *   If your project uses a different UART or you don't want traces, remove
 *   the heap_dbg calls or change to another debug mechanism.
 */

#include "heap_driver.h"
#include "stddef.h"
#include "stdint.h"
#include "string.h"

/* For debug prints (optional). Uses huart1 from main.c -- your project already
   defines huart1 in main.c generated by CubeMX. */
#include "stm32f3xx_hal.h"
extern UART_HandleTypeDef huart1; /* must exist in the project */

static void heap_dbg(const char *s)
{
    if (s == NULL) return;
    /* finite timeout */
    HAL_UART_Transmit(&huart1, (uint8_t*)s, (uint16_t)strlen(s), 200);
}

/* Configuration */
#define HEAP_START_ADDR   ((uintptr_t)0x20001000U)
#define HEAP_SIZE_BYTES   (4096U)
#define HEAP_BLOCK_SIZE   (16U)
#define HEAP_BLOCK_COUNT  (HEAP_SIZE_BYTES / HEAP_BLOCK_SIZE)

/* Sanity check */
#if (HEAP_SIZE_BYTES % HEAP_BLOCK_SIZE) != 0
#error "HEAP_SIZE_BYTES must be multiple of HEAP_BLOCK_SIZE"
#endif

/* block map: stored in normal data memory (not inside heap region) */
static uint8_t block_map[HEAP_BLOCK_COUNT];

/* pointer to heap base (byte pointer) */
static uint8_t * const heap_base = (uint8_t *)HEAP_START_ADDR;

void heap_init(void)
{
    /* mark all blocks free */
    memset(block_map, 0, sizeof(block_map));
    heap_dbg("heap_init: block_map cleared\r\n");
}

/* Return total heap size in bytes */
size_t heap_total_size(void) { return HEAP_SIZE_BYTES; }
/* Return block size */
size_t heap_block_size(void) { return HEAP_BLOCK_SIZE; }
/* Return block count */
size_t heap_block_count(void) { return HEAP_BLOCK_COUNT; }

/* Helper: find contiguous free run of 'need' blocks; return start index or -1 */
static int find_free_run(size_t need)
{
    size_t run = 0;
    for (size_t i = 0; i < HEAP_BLOCK_COUNT; ++i) {
        if (block_map[i] == 0) {
            run++;
            if (run == need) {
                return (int)(i + 1 - need);
            }
        } else {
            run = 0;
        }
    }
    return -1;
}

void *heap_alloc(size_t size)
{
    if (size == 0 || size > HEAP_SIZE_BYTES) {
        heap_dbg("heap_alloc: invalid size\r\n");
        return NULL;
    }

    /* how many blocks needed */
    size_t need = (size + HEAP_BLOCK_SIZE - 1) / HEAP_BLOCK_SIZE;
    if (need == 0 || need > HEAP_BLOCK_COUNT) {
        heap_dbg("heap_alloc: need out of range\r\n");
        return NULL;
    }

    int idx = find_free_run(need);
    if (idx < 0) {
        heap_dbg("heap_alloc: no contiguous region found\r\n");
        return NULL;
    }

    /* mark blocks: head = 2, following = 1 */
    block_map[idx] = 2;
    for (size_t k = 1; k < need; ++k) {
        block_map[idx + k] = 1;
    }

    /* return pointer to the start address */
    uintptr_t addr = HEAP_START_ADDR + (uintptr_t)idx * HEAP_BLOCK_SIZE;
    char buf[80];
    int n = snprintf(buf, sizeof(buf), "heap_alloc: %u bytes -> idx %d addr 0x%08lX\r\n",
                     (unsigned)size, idx, (unsigned long)addr);
    if (n > 0) heap_dbg(buf);

    return (void *)addr;
}

void heap_free(void *ptr)
{
    if (ptr == NULL) {
        heap_dbg("heap_free: NULL pointer\r\n");
        return;
    }

    uintptr_t uptr = (uintptr_t)ptr;
    /* check within heap range */
    if (uptr < HEAP_START_ADDR || uptr >= (HEAP_START_ADDR + HEAP_SIZE_BYTES)) {
        heap_dbg("heap_free: pointer out of heap range\r\n");
        return;
    }

    /* must be block-aligned */
    uintptr_t offset = uptr - HEAP_START_ADDR;
    if ((offset % HEAP_BLOCK_SIZE) != 0) {
        heap_dbg("heap_free: pointer not block-aligned\r\n");
        return;
    }

    size_t idx = offset / HEAP_BLOCK_SIZE;
    if (idx >= HEAP_BLOCK_COUNT) {
        heap_dbg("heap_free: index out of range\r\n");
        return;
    }

    if (block_map[idx] == 0) {
        heap_dbg("heap_free: double free or invalid pointer (already free)\r\n");
        return;
    }

    /* Clear head */
    block_map[idx] = 0;

    /* Clear subsequent continuation blocks (1) until we hit 0 or a head (2),
       or until end of block_map. Note: we stop at a 2 (next allocation head),
       which prevents freeing into adjacent allocations. */
    size_t i = idx + 1;
    while (i < HEAP_BLOCK_COUNT) {
        if (block_map[i] == 1) {
            block_map[i] = 0;
            i++;
            continue;
        }
        /* stop on 0 (free) or 2 (next allocation head) */
        break;
    }

    char buf[80];
    int n = snprintf(buf, sizeof(buf), "heap_free: freed idx %u (next idx %u)\r\n",
                     (unsigned)idx, (unsigned)i);
    if (n > 0) heap_dbg(buf);
}
